packages:
  - core/*
  - packages/*
  - packages/annotations/**/*
  - packages/subscribables/**/*
  - meta/*
  - sites/*
  - tools/*
  - tools/*/*

catalog:
  "@automerge/automerge": 3.2.4
  "@automerge/automerge-repo-keyhive": 0.1.0-alpha.14
  "@keyhive/keyhive": 0.0.0-alpha.54
  "@types/react": 18.3.1
  "@types/react-dom": 18.3.1
  react: 18.3.1
  react-dom: 18.3.1

overrides:
  "@automerge/automerge": 3.2.4
  react: 18.3.1
  react-dom: 18.3.1
