packages:
  - core/*
  - packages/*
  - packages/annotations/**/*
  - packages/subscribables/**/*
  - meta/*
  - sites/*
  - tools/*
  - tools/*/*

catalog:
  "@automerge/automerge": 3.2.1
  "@automerge/automerge-repo": 2.5.2-alpha.0
  "@automerge/automerge-repo-keyhive": 0.1.0-alpha.14
  "@automerge/automerge-repo-react-hooks": 2.5.2-alpha.0
  "@automerge/automerge-repo-solid-primitives": 2.4.0
  "@automerge/react": 2.5.2-alpha.0
  "@automerge/vanillajs": 2.5.2-alpha.0
  "@keyhive/keyhive": 0.0.0-alpha.54
  "@types/react": ^18.3.27
  "@types/react-dom": ^18.3.7

overrides:
  "@automerge/automerge-repo": link:../automerge-repo/packages/automerge-repo
  "@automerge/automerge-repo-react-hooks": link:../automerge-repo/packages/automerge-repo-react-hooks
  "@automerge/automerge-repo-solid-primitives": link:../automerge-repo/packages/automerge-repo-solid-primitives
  "@automerge/automerge-repo-subduction-bridge": link:../automerge-repo/packages/automerge-repo-subduction-bridge
  "@automerge/automerge_subduction": link:../subduction/automerge_subduction_wasm
  "@automerge/vanillajs": link:../automerge-repo/packages/automerge-vanillajs
  react: 18.3.26
  react-dom: 18.3.7
