import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Tabs, TabsList, TabsTrigger } from "@patchwork/sdk/ui";
import { ChevronsRight, MessageSquareIcon, HistoryIcon, BotIcon, } from "lucide-react";
import { TimelineSidebar } from "./TimelineSidebar";
import { ReviewSidebar } from "./ReviewSidebar";
import { BotSidebar } from "./BotSidebar";
export function VersionControlSidebar({ docUIState, changeDocUIState, onChangeSidebarMode, dataType, cloneOrMainOm, setDocHeadsFromTimelineSidebar, setDiffFromTimelineSidebar, branchScopeAndActiveBranchInfo, onSelectBranch, cloneOrMainDocAtHeads, docHeadsFromTimelineSidebar, tool, filteredAnnotationGroups, selectedAnchors, setHoveredAnnotationGroupId, setSelectedAnnotationGroupId, isCommentInputFocused, setIsCommentInputFocused, setCommentState, docLink, onMergeBranch, onDeleteBranch, }) {
    return (docUIState.sidebarMode && (_jsxs("div", { className: "border-l border-gray-200 py-2 h-full flex flex-col relative bg-gray-50", children: [_jsx("div", { className: "-left-[33px] absolute cursor-pointer hover:bg-gray-100 border hover:border-gray-500 rounded-lg w-[24px] h-[24px] grid place-items-center", onClick: () => changeDocUIState((state) => delete state.sidebarMode), children: _jsx(ChevronsRight, { size: 16 }) }), _jsx("div", { className: "px-2 pb-2 flex flex-col gap-2 text-sm font-semibold text-gray-600 border-b border-gray-200", children: _jsx(Tabs, { value: docUIState.sidebarMode, onValueChange: onChangeSidebarMode, children: _jsxs(TabsList, { className: "grid w-full grid-cols-3", children: [_jsxs(TabsTrigger, { value: "review", children: [_jsx(MessageSquareIcon, { size: 16, className: "mr-2" }), "Review"] }), _jsxs(TabsTrigger, { value: "history", children: [_jsx(HistoryIcon, { size: 16, className: "mr-2" }), "History"] }), _jsxs(TabsTrigger, { value: "bot", children: [_jsx(BotIcon, { size: 16, className: "mr-2" }), "Bot"] })] }) }) }), _jsxs("div", { className: "min-h-0 flex-grow w-96", children: [docUIState.sidebarMode === "history" && dataType && (_jsx(TimelineSidebar
                    // set key to trigger re-mount on branch change
                    , { dataType: dataType, docUrl: cloneOrMainOm.url, setDocHeads: setDocHeadsFromTimelineSidebar, setDiff: setDiffFromTimelineSidebar, branchScopeAndActiveBranchInfo: branchScopeAndActiveBranchInfo, onSelectBranchUrl: onSelectBranch }, cloneOrMainOm.url)), docUIState.sidebarMode === "review" &&
                        cloneOrMainDocAtHeads &&
                        cloneOrMainOm && (_jsx(ReviewSidebar, { doc: cloneOrMainDocAtHeads, handle: cloneOrMainOm.handle, readonly: !!docHeadsFromTimelineSidebar, tool: tool, annotationGroups: filteredAnnotationGroups, selectedAnchors: selectedAnchors, setHoveredAnnotationGroupId: setHoveredAnnotationGroupId, setSelectedAnnotationGroupId: setSelectedAnnotationGroupId, isCommentInputFocused: isCommentInputFocused, setIsCommentInputFocused: setIsCommentInputFocused, setCommentState: setCommentState })), docUIState.sidebarMode === "bot" &&
                        cloneOrMainDocAtHeads &&
                        cloneOrMainOm &&
                        dataType && (_jsx(BotSidebar, { doc: cloneOrMainDocAtHeads, handle: cloneOrMainOm.handle, mainDocUrl: docLink.url, dataType: dataType, selectedBranchUrl: branchScopeAndActiveBranchInfo.activeBranchOm?.url, setSelectedBranch: onSelectBranch, setSidebarMode: onChangeSidebarMode, onMergeBranch: onMergeBranch, onDeleteBranch: onDeleteBranch }))] })] })));
}
