name: TypeScript & Vitest Check

on:
  push:
    branches: [main, jacquard]
  pull_request:
    branches: [main, jacquard]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript compiler
        run: pnpm tsc

      - name: Run tests
        run: pnpm test
        # see https://stackoverflow.com/q/58858429
        if: success() || failure()
